on:
  push:
    branches: [main]
  workflow_dispatch:

name: Quarto Publish

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # 升级到 v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto project
        run: quarto render

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 升级到 v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 升级到 v4